version: "3.8"

services:
  shard3svr1:
    container_name: shard3svr1
    restart: on-failure
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 50007:27017
    volumes:
      - shard3svr1:/data/db

  shard3svr2:
    container_name: shard3svr2
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 50008:27017
    volumes:
      - shard3svr2:/data/db

  shard3svr3:
    container_name: shard3svr3
    image: mongo
    command: mongod --shardsvr --bind_ip_all --replSet shard3rs --port 27017 --dbpath /data/db
    ports:
      - 50009:27017
    volumes:
      - shard3svr3:/data/db

volumes:
  shard3svr1: {}
  shard3svr2: {}
  shard3svr3: {}
